# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artboard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('hash_tag', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
