# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160319_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='artboard_owner_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artboard_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
    ]
