# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160319_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artboard_owner_relation',
            new_name='ArtboardOwnerRelation',
        ),
        migrations.RenameModel(
            old_name='ingredient_images',
            new_name='IngredientImages',
        ),
    ]
